spring:
  application:
    name: github-action

  threads:
    virtual:
      enabled: true

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
